version: '3.3'

volumes:
  static_value:
  media_value:
  database:

services:
  db:
    image: postgres:13.0-alpine
    container_name: db-fragments
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: rasputin21/fragments:latest
    container_name: web-fragments
    restart: unless-stopped
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    restart: unless-stopped
    container_name: nginx-fragments
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
